
import type { University } from './types.ts'

export function getSampleUniversities(): University[] {
  return [
    {
      name: 'Harvard University',
      alpha_two_code: 'US',
      web_pages: ['http://www.harvard.edu/'],
      domains: ['harvard.edu'],
      country: 'United States',
      state_province: 'Massachusetts',
      city: 'Cambridge',
      latitude: 42.3744,
      longitude: -71.1169,
      region: 'North America',
      min_gpa: 3.9,
      min_sat_score: 1520,
      min_ielts_score: 7.5,
      min_duolingo_score: 130,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 5
    },
    {
      name: 'Massachusetts Institute of Technology',
      alpha_two_code: 'US',
      web_pages: ['http://web.mit.edu/'],
      domains: ['mit.edu'],
      country: 'United States',
      state_province: 'Massachusetts',
      city: 'Cambridge',
      latitude: 42.3601,
      longitude: -71.0942,
      region: 'North America',
      min_gpa: 4.0,
      min_sat_score: 1550,
      min_ielts_score: 7.0,
      min_duolingo_score: 125,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 6
    },
    {
      name: 'Stanford University',
      alpha_two_code: 'US',
      web_pages: ['https://www.stanford.edu/'],
      domains: ['stanford.edu'],
      country: 'United States',
      state_province: 'California',
      city: 'Stanford',
      latitude: 37.4275,
      longitude: -122.1697,
      region: 'North America',
      min_gpa: 3.95,
      min_sat_score: 1530,
      min_ielts_score: 7.0,
      min_duolingo_score: 125,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 4
    },
    {
      name: 'University of Oxford',
      alpha_two_code: 'GB',
      web_pages: ['http://www.ox.ac.uk/'],
      domains: ['ox.ac.uk'],
      country: 'United Kingdom',
      state_province: null,
      city: 'Oxford',
      latitude: 51.7548,
      longitude: -1.2544,
      region: 'Europe',
      min_gpa: 3.8,
      min_sat_score: null,
      min_ielts_score: 7.0,
      min_duolingo_score: 120,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 17
    },
    {
      name: 'University of Cambridge',
      alpha_two_code: 'GB',
      web_pages: ['http://www.cam.ac.uk/'],
      domains: ['cam.ac.uk'],
      country: 'United Kingdom',
      state_province: null,
      city: 'Cambridge',
      latitude: 52.2043,
      longitude: 0.1149,
      region: 'Europe',
      min_gpa: 3.85,
      min_sat_score: null,
      min_ielts_score: 7.5,
      min_duolingo_score: 130,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 21
    },
    {
      name: 'California Institute of Technology',
      alpha_two_code: 'US',
      web_pages: ['https://www.caltech.edu/'],
      domains: ['caltech.edu'],
      country: 'United States',
      state_province: 'California',
      city: 'Pasadena',
      latitude: 34.1377,
      longitude: -118.1253,
      region: 'North America',
      min_gpa: 4.0,
      min_sat_score: 1560,
      min_ielts_score: 7.0,
      min_duolingo_score: 130,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 6
    },
    {
      name: 'ETH Zurich',
      alpha_two_code: 'CH',
      web_pages: ['https://ethz.ch/'],
      domains: ['ethz.ch'],
      country: 'Switzerland',
      state_province: null,
      city: 'Zurich',
      latitude: 47.3769,
      longitude: 8.5417,
      region: 'Europe',
      min_gpa: 3.5,
      min_sat_score: null,
      min_ielts_score: 7.0,
      min_duolingo_score: 115,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 27
    },
    {
      name: 'University of Toronto',
      alpha_two_code: 'CA',
      web_pages: ['https://www.utoronto.ca/'],
      domains: ['utoronto.ca'],
      country: 'Canada',
      state_province: 'Ontario',
      city: 'Toronto',
      latitude: 43.6629,
      longitude: -79.3957,
      region: 'North America',
      min_gpa: 3.6,
      min_sat_score: 1400,
      min_ielts_score: 6.5,
      min_duolingo_score: 110,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 43
    },
    {
      name: 'National University of Singapore',
      alpha_two_code: 'SG',
      web_pages: ['https://www.nus.edu.sg/'],
      domains: ['nus.edu.sg'],
      country: 'Singapore',
      state_province: null,
      city: 'Singapore',
      latitude: 1.2966,
      longitude: 103.7764,
      region: 'Asia',
      min_gpa: 3.7,
      min_sat_score: 1450,
      min_ielts_score: 6.5,
      min_duolingo_score: 110,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 5
    },
    {
      name: 'Tsinghua University',
      alpha_two_code: 'CN',
      web_pages: ['https://www.tsinghua.edu.cn/'],
      domains: ['tsinghua.edu.cn'],
      country: 'China',
      state_province: null,
      city: 'Beijing',
      latitude: 40.0069,
      longitude: 116.3226,
      region: 'Asia',
      min_gpa: 3.7,
      min_sat_score: null,
      min_ielts_score: 6.5,
      min_duolingo_score: 110,
      degree_types: ['Bachelor', 'Master', 'PhD'],
      scholarships_available: true,
      acceptance_rate: 2
    }
  ]
}
