
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://naryscybybqcuursbwec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hcnlzY3lieWJxY3V1cnNid2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNTc0OTUsImV4cCI6MjA1OTgzMzQ5NX0.WyWSeaBgXLXVQRb22szDEhNwieEdtbVmkyABL5ZKsDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use the createClient function with a more permissive type to allow any table
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
